include: package:lints/recommended.yaml

analyzer:
  errors:
    # Just need to clean up existing violations.
    non_constant_identifier_names: ignore
    todo: ignore
  language:
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - avoid_catches_without_on_clauses
    - avoid_positional_boolean_parameters
    - avoid_unused_constructor_parameters
    - directives_ordering
    - package_api_docs
    - prefer_asserts_in_initializer_lists
    - prefer_if_elements_to_conditional_expressions
    - unnecessary_parenthesis
